// Code generated by xbit. DO NOT EDIT.
package event

import (
	"github.com/xbitgo/components/eventbus"
)

func Register() {
	// eventbus初始化
	eventbus.Init()
	// 自定义事件注册
	eventbus.RegisterCustomEvent(NewCustomEvent())
}
