// Code generated by xbit. DO NOT EDIT.
package entry

import (
	"github.com/gin-gonic/gin"

	pb "xbitgo/proto/apps/demo"

	"xbitgo/common/ecode"
	"xbitgo/common/http_io"
)

func DemoHttpInit(r *gin.Engine, impl pb.DemoServer) {

	//  Test
	r.POST("/api/demo/test", func(ctx *gin.Context) {
		var req = &pb.TestRequest{}
		if err := http_io.BindBody(ctx, &req); err != nil {
			http_io.JSONError(ctx, ecode.ErrParams)
			return
		}
		res, err := impl.Test(http_io.Metadata(ctx), req)
		http_io.JSON(ctx, res, err)
	})

}
